### ISSUE TITLE
INSTALL instructions incomplete, automake invocation?

### ISSUE THREAD

**Issue by neuhaus** [quozl/netrek-server#3]
The repository does not have the `configure` script mentioned in the `INSTALL` file.

I tried to create it myself using `aclocal`, then `automake --add-missing`, however got this error:

```
$ aclocal
aclocal: warning: autoconf input should be named 'configure.ac', not 'configure.in'
$ automake --add-missing
automake: warning: autoconf input should be named 'configure.ac', not 'configure.in'
configure.in: error: no proper invocation of AM_INIT_AUTOMAKE was found.
configure.in: You should verify that configure.in invokes AM_INIT_AUTOMAKE,
configure.in: that aclocal.m4 is present in the top-level directory,
configure.in: and that aclocal.m4 was recently regenerated (using aclocal)
automake: error: no 'Makefile.am' found for any configure output

```

The automake I'm using is version 1.15-4ubuntun1.

**Comment by quozl** [comment]
Run `autogen.sh` after clone.

Tested on Ubuntu 16.04 with updates.  Needed `libgdbm-dev`.

**Comment by neuhaus** [comment]
Thanks. Do you want to add it to the INSTALL file? I also had to install the `libtool` package.

What packages are required to do a RSA install?

**Comment by quozl** [comment]
No, `INSTALL` should be distribution agnostic.  I'd like to add to `README.md`, but I'll need to find the other dependencies first.  There's an indicative list in `debian/control` but it needs to be verified against each Ubuntu or Debian release.  Combinatorial explosion.
