### ISSUE TITLE
Ships missing in hockey

### ISSUE THREAD

**Issue by bgloyer** [quozl/netrek-server#5]
This what I saw when the ships were missing ships in hockey.

The ships are not visible on either the tactical or galactic.  However torps and phasors they shoot are.  I noticed it on the faceoffs.  I never saw a ship just disappear though it could have happened when they res'd.   A request for a full update had no effect.  It seemed like once the invisible ship was killed, it would be back to normal after it came back.  Other players seemed to be able to see the invisible ship, but at least one other person saw the problem at the same time I did.  (they were playing from Windows).

It happens with a more crowded field.  We played 2x2 (with no observers) afterwards and never saw the problem.  

I was using BRMH-2.5 on linux
@hyperyoda 

edits by @quozl follow
* does not happen until t-mode,
* happens with 64-bit or 32-bit compilation,
* a reset to TCP has no effect on the problem,
* clients affected BRMH-2.5, COW, XP Mod 4.4.0.4, XP 2010, XP 2009,

**Comment by hyperyoda** [comment]
Interesting.

**Comment by bgloyer** [comment]
Some more clues:

I was able to recreate this on a local server with local clients with no observers.

It happens after a goal is scored.

All clients see the same ships missing. 

I didn't notice any pattern about which ships were missing, it wasn't the same ones every time.

All ships on your team are always visible.

An invisible ship always becomes visible after it is killed.
